name: Deploy IDT Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh

          cat > ~/.ssh/id_ed25519 << 'EOF'
            ${{ secrets.VPS_SSH_KEY }}
          EOF

          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH File
        run: |
          echo "File size:"
          wc -c ~/.ssh/id_ed25519

          echo "First line:"
          head -n 1 ~/.ssh/id_ed25519

          echo "Last line:"
          tail -n 1 ~/.ssh/id_ed25519
      - name: Verify SSH key
        run: |
          ssh-keygen -y -f ~/.ssh/id_ed25519

      - name: Deploy on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
          EOF
