name: Deploy IDT Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.VPS_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

      - name: Verify SSH Key
        run: |
          ssh-keygen -y -f ~/.ssh/id_ed25519

      - name: Show Runner IP
        run: |
          curl -4 ifconfig.me

      - name: Test SSH Connectivity
        run: |
          timeout 15 bash -c "</dev/tcp/${{ secrets.VPS_HOST }}/22" \
          && echo "SSH PORT OPEN" \
          || echo "SSH PORT BLOCKED"

      - name: Deploy on VPS
        run: |
          for i in 1 2 3 4 5
          do
            echo "Attempt $i"

            ssh \
              -o StrictHostKeyChecking=no \
              -o ConnectTimeout=20 \
              -i ~/.ssh/id_ed25519 \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo Connected" && break

            sleep 15
          done

          ssh \
            -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_ed25519 \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
          EOF
